---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
sum(aLogical)
```

```{r}
aLogical <- c(F,TRUE,F,FALSE,FALSE)
class(aLogical)
sum(aLogical)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```
```{r}
class(studentMajors)
```

```{r}
studentMajors0 <- 
  c("經濟系", "經濟系", "法律系")
```

```{r}
class(studentMajors0)
```

```{r}
birthplace <- factor(
  c("台北", "台中", "台北", "台中", "台中")
)
```


```{r}
typeof(birthplace)
```

```{r}
levels(birthplace)
```

```{r}
birthplace
```

```{r}
as.integer(birthplace)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
```

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```

```{r}
stringInteger
trueInteger
```

```{r}
sum(trueInteger)
```

```{r}
install.packages(c("lubridate"),lib="C:/rpackages")
```

```{r}
library(lubridate,lib="C:/rpackages")
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
dtObject
```

```{r}
typeof(dtObject)
```

```{r}
as.integer(dtObject)
```

```{r}
as.double(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")

twDateTime
```


```{r}
LisbonDateTime <- dmy_h("27-03-2019 15")
LisbonDateTime
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
```

```{r}
twDateTime <- ymd_hms("2019-04-01 04:01:00", tz="Asia/Taipei")

USDateTime <- with_tz(twDateTime,tzone = "America/New_York")
```

```{r}
twDateTime<-ymd_hms("2019-03-27 15:39:44", tz="Asia/Taipei")
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
typeof(LisbonDateTime)
as.double(LisbonDateTime)
as.double(twDateTime)
```

```{r}
TWDT <- dmy_h("27-03-2019 15")
TWDT
```

```{r}
install.packages(c("lubridate"),lib="C:/rpackages")
library(lubridate,lib="C:/rpackages")
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
as.double(twDateTime)
as.integer(twDateTime)
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
twDateTime
```

```{r}
ymd("1970-01-01") %>% as.integer
ymd("1970-01-02") %>% as.integer
ymd("2019-03-11") %>% as.integer
```








```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
a+b
a-b
a*b
a/b
class(a+b)
```

```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
a+bL
aL+bL
class(a+bL)
class(aL+bL)
```

```{r}
a^b
a %% b
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime*2
as.interger(twDateTime*2)
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime+100
ymd("2019-08-11")-ymd("2000-02-01")
ymd_hms("2019-03-18 14:04:00")-ymd_hms("2019-03-18 14:02:00")
```

```{r}
twDateTime <- mdy_hms("03-18-1960 14:04:00", tz="Asia/Taipei")
twDateTime
as.integer(twDateTime)
```

```{r}
time1 <- ymd("2019-08-11")
time2 <- ymd("2000-02-01")
time1-time2
class(time1-time2)
class(time1)
```

```{r}
startingDate <- ymd("2000-02-17")
as.integer(startingDate)
```

```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1)
startingDate + dyears(1)
```



```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```

```{r}
x <- 5
y <- 7

x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x > y
x == y
x < y
x == y2
x2 < y
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
x3 == y3
x3 != y3
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```

```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```

```{r}
x2
y2
x2 == y2
is.na(x2)
```

```{r}
sum(x2)
sum(x2, na.rm = TRUE)
sum(x2, na.rm = FALSE)
```

```{r}
0/0
```

```{r}
install.packages(c("crayon"),lib="C:/rpackages")
library(crayon,lib="C:/rpackages")
```


```{r}
install.packages(c("readr"),lib="C:/rpackages")
library(readr,lib="C:/rpackages")
```


```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```

```{r}
head(currency)
```

```{r}
class(currency)
```

```{r}
currency <- as.factor(currency)
```


```{r}
levels(currency)
```

```{r}
length(levels(currency))
```

```{r}
sum(currency == "日圓JPY/USD")
```

```{r}
sum(currency == "人民幣CNY/USD")
```

```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)
```

```{r}
y5 <- c("女","男","女")

y5
y5=="女"
!(y5=="女")
```

```{r}
x5 %in% greatTaipei
y5=="女"
(x5 %in% greatTaipei) & (y5=="女")
(x5 %in% greatTaipei) | (y5=="女")
xor(x5 %in% greatTaipei, y5=="女")
which((x5 %in% greatTaipei) & (y5=="女"))
which((x5 %in% greatTaipei) | (y5=="女"))
which(xor(x5 %in% greatTaipei, y5=="女"))
```

```{r}
y5
(y5 == "女")
which(y5=="女")
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```

```{r}
install.packages("stringr")
library(stringr)
```


```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績
```


```{r}
course <- c("個體經濟學","投資學","總體經濟學")
```

```{r}
month <- c("3","4","2")
day <- c("11","5","7")
```

```{r}
chineseDate <- c("3月11日","4月5日","2月7日")
```

```{r}
str_subset(course,"經濟學")
```

```{r}
str_detect(course,"經濟學")
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
```

```{r}
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```

```{r}
str_c(month,c("月"),day,c("日"))
str_c(month,"月",day,"日")
```

```{r}
month
day
str_c(month,day, sep="-")
```

```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```

```{r}
dates
str_replace(dates,"-","月")
```

```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
str_c("https://github.com",username,reponame,sep = "/")
```


```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```

```{r}

birthday[1:2]
y<-str_sub(birthday[1:2],1,4)
m<-str_sub(birthday[1:2],5,6)
d<-str_sub(birthday[1:2],7,8)
bday<-str_c("西元",y,"年",m,"月",d,"日")
bday
```

```{r}
民國年月<-c("099/01","099/02","099/03")
```

```{r}
民國年月<-c("099/01","099/02","099/03")
y<- str_sub(民國年月,2,3)
m<- str_sub(民國年月,5,6)
y2<- as.integer(y)
m2<- as.integer(m)
str_c("西元",y2+1911,"年",m2,"月")
```




```{r}
a<-c(1:3)
typeof(a)
a
```

```{r}
aWithNames <- c(
  a1=1,
  a2=2,
  a3=3
)
typeof(a)
aWithNames
```

```{r}
b1<-list("a","b",c(1:10))
typeof(b1)
```

```{r}
b2<-list(
  第一個="a",
  第二個="b",
  第三個=c(1:10))
```

```{r}
b1
b2
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```

```{r}
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```

```{r}
x <- plasticContainer[["greenBox"]] 
x[[1]]
```

```{r}
plasticContainer[["greenBox"]][[1]]
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
成績單[['個經']]
成績單[[1]]
```

```{r}
studentRecord[["姓名"]]
studentRecord[["學年平均成績"]] [[3]]
```

```{r}
plasticContainer[c("greenBox","redBox")] 
plasticContainer[c(1,2)]
```

```{r}
list(
  greenBox=c("paper","scissor"),
  redBox=c(1,3,2.5)
)
```

```{r}
extract1 <- plasticContainer[c("greenBox")]
```

```{r}
extract2 <- plasticContainer[[c("greenBox")]]
```

```{r}
extract1[[1]][[1]]
extract2[[1]]
```

```{r}
length(plasticContainer)
plasticContainer[c(T,F,T)]
```

```{r}
成績單
成績單[c(FALSE,TRUE,TRUE)]
```

```{r}
plasticContainer$greenBox
plasticContainer[["greenBox"]]
```

```{r}
your_github_username <- "amypiggy"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
```

```{r}
commitCheck[[4]][["commit"]][["committer"]][["date"]] -> commitDate
ymd_hms(commitDate) -> commitDate
with_tz(commitDate.tzone="Asia/Taipei")
```

```{r}
commitCheck[[4]]$commit[["committer"]][["date"]]
```

```{r}
committwtime <- commitCheck[[4]][[3]][[2]][[3]]
class(commitCheck[[4]][[3]][[2]][[3]])
committwtime <- ymd_hms(committwtime)
class(committwtime)
Sys.timezone()
twTime <- with_tz(committwtime,tzone="Asia/Taipei")
twTime
```


```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```

```{r}
logiCorrect <- str_length(birthday)==8
logiCorrect
```

```{r}
favoriteTwo[logiCorrect] -> validFavoriteTwo
validFavoriteTwo
```


```{r}
library(stringr)
str_split(favoriteTwo,", ") -> favoriteTwoList # 將選擇的兩片split成兩個元素
unlist(favoriteTwoList) -> allVotes # 將list堆疊成atomic vector
table(allVotes) # 計算每個類別的次數
```

```{r}
Mat1 <- matrix(
  c(1:6), 2,3
)
Mat1
```

```{r}
class(Mat1)
```

```{r}
typeof(Mat1)
```

```{r}
Mat2 <- matrix(
  c("a","b","c","d"), 2, 2
)
Mat2
```

```{r}
MAT2 <- matrix(c("a","b","c","d"),2,2)
MAT2
class(MAT2)
typeof(MAT2)
MAT2[[2]]
MAT2[c(T,F,F,T)]
```


```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
StuList[[2]][3]
```


```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
class(StuDF$姓名)
```

```{r}
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```

```{r}
class(StuList)
```

```{r}
as.data.frame(StuList) -> StuDF3

class(StuDF3)
```

```{r}
StuDF3
```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
```

```{r}
StuDF4
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
class(StuDF)
```

```{r}
typeof(StuDF)
```


```{r}
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```

```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m)
```

```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m) # 轉成小寫
m
toupper(m) # 轉成大寫
m
```


```{r}
chosenLETTERS[8]
```

```{r}
matObj1[8]
```

```{r}
matObj1
```

```{r}
matObj1[3,2] 
```

```{r}
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
```

```{r}
StuDF
```

```{r}
StuDF[c("姓名","成績")] 
```

```{r}
StuDF[1:5,c("姓名","成績")] 
```

```{r}
StuDF[,c("姓名","成績")]
```

```{r}
matObj1[,3]
```

```{r}
cbind(matObj1,letters[1:5])
```

```{r}
matObj1[c(T,F,F,T,F),c(F,T,T)]
```


```{r}
StuDF
```

```{r}
StuList
```

```{r}
StuDF[4,c("成績")]
```

```{r}
Vector1 <- letters[1:6]
Vector1
```

```{r}
names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Mat1
```

```{r}
names(Mat1) 
```

```{r}
names(Mat1) <- letters[1:6]
names(Mat1)
```

```{r}
matObj1
```

```{r}
colnames(matObj1) 
rownames(matObj1)
```

```{r}
colnames(matObj1) <-c('欄位1','欄位2','欄位3')
colnames(matObj1)
matObj1
```

```{r}
rownames(matObj1) <- c('行：1','行：2','行：3','行：4','行：5')
matObj1
```

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b$元素2<-"hi"
b$新成員 <-c(2,5,1)
b
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

```{r}
exData3$期間 <- ymd(exData3$期間)
class(exData3$期間)
```

```{r}
exData3$isAsiaCrisis <- exData3$期間 >= ymd("1997-06-01") & exData3$期間 <= ymd("1998-12-01")
class(exData3$isAsiaCrisis)
```

```{r}
logiAsiaCrisis <- exData3$isAsiaCrisis
exData3[logiAsiaCrisis, ]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```


```{r}
OMG <- function(x,.alpha){OMGValue <- x+.alpha
return(OMGValue)
}
```

```{r}
OMG(2,2)
```

```{r}
supply_fun <- function(a,b,P){
  Qs <- a+b*P
  return(Qs)
}
```

```{r}
demand_fun <- function(c,d,P){
  Qd <- c-d*P
  return(Qd)
}
```

```{r}
supply_fun(0,1,1)
demand_fun(5,1,1)
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```


```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```

```{r}
classSurvey[,4:5]
classSurvey[,c(4,5)]
classSurvey[,c(F,F,F,T,T,F)]
```

```{r}
classSurvey[c(1:60),c(4,5)]
```

Midterm
```{r}
https://drive.google.com/drive/folders/12_9n6c74qF6xu49VLCouEJS2ag3o9dBN?usp=sharing
```

