---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
sum(aLogical)
```

```{r}
aLogical <- c(F,TRUE,F,FALSE,FALSE)
class(aLogical)
sum(aLogical)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```
```{r}
class(studentMajors)
```

```{r}
studentMajors0 <- 
  c("經濟系", "經濟系", "法律系")
```

```{r}
class(studentMajors0)
```

```{r}
birthplace <- factor(
  c("台北", "台中", "台北", "台中", "台中")
)
```


```{r}
typeof(birthplace)
```

```{r}
levels(birthplace)
```

```{r}
birthplace
```

```{r}
as.integer(birthplace)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
```

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```

```{r}
stringInteger
trueInteger
```

```{r}
sum(trueInteger)
```

```{r}
install.packages(c("lubridate"),lib="C:/rpackages")
```

```{r}
library(lubridate,lib="C:/rpackages")
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
dtObject
```

```{r}
typeof(dtObject)
```

```{r}
as.integer(dtObject)
```

```{r}
as.double(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")

twDateTime
```


```{r}
LisbonDateTime <- dmy_h("27-03-2019 15")
LisbonDateTime
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
```

```{r}
twDateTime <- ymd_hms("2019-04-01 04:01:00", tz="Asia/Taipei")

USDateTime <- with_tz(twDateTime,tzone = "America/New_York")
```

```{r}
twDateTime<-ymd_hms("2019-03-27 15:39:44", tz="Asia/Taipei")
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
typeof(LisbonDateTime)
as.double(LisbonDateTime)
as.double(twDateTime)
```

```{r}
TWDT <- dmy_h("27-03-2019 15")
TWDT
```

```{r}
install.packages(c("lubridate"),lib="C:/rpackages")
library(lubridate,lib="C:/rpackages")
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
as.double(twDateTime)
as.integer(twDateTime)
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
twDateTime
```

```{r}
ymd("1970-01-01") %>% as.integer
ymd("1970-01-02") %>% as.integer
ymd("2019-03-11") %>% as.integer
```








```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
a+b
a-b
a*b
a/b
class(a+b)
```

```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
a+bL
aL+bL
class(a+bL)
class(aL+bL)
```

```{r}
a^b
a %% b
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime*2
as.interger(twDateTime*2)
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime+100
ymd("2019-08-11")-ymd("2000-02-01")
ymd_hms("2019-03-18 14:04:00")-ymd_hms("2019-03-18 14:02:00")
```

```{r}
twDateTime <- mdy_hms("03-18-1960 14:04:00", tz="Asia/Taipei")
twDateTime
as.integer(twDateTime)
```

```{r}
time1 <- ymd("2019-08-11")
time2 <- ymd("2000-02-01")
time1-time2
class(time1-time2)
class(time1)
```

```{r}
startingDate <- ymd("2000-02-17")
as.integer(startingDate)
```

```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1)
startingDate + dyears(1)
```



```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```

```{r}
x <- 5
y <- 7

x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x > y
x == y
x < y
x == y2
x2 < y
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
x3 == y3
x3 != y3
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```

```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```

```{r}
x2
y2
x2 == y2
is.na(x2)
```

```{r}
sum(x2)
sum(x2, na.rm = TRUE)
sum(x2, na.rm = FALSE)
```

```{r}
0/0
```

